export const AUDIT_ROLES = ["admin", "faculty", "student"] as const;
export type AuditRole = (typeof AUDIT_ROLES)[number];

export const AUDIT_SEVERITY = ["low", "medium", "high"] as const;
export type AuditSeverity = (typeof AUDIT_SEVERITY)[number];

export const AUDIT_STATUS = ["success", "failed"] as const;
export type AuditStatus = (typeof AUDIT_STATUS)[number];

/** Values match Mongoose model names so `entityId` can be resolved against the right collection. */
export const AUDIT_ENTITY_TYPE = {
  USER: "User",
  STUDENT: "Student",
  FACULTY: "Faculty",
  CLASS: "Class",
  CLASS_ENROLLMENT: "ClassEnrollement",
  SUBJECT: "Subject",
  SUBJECT_FACULTY_ASSIGNMENT: "SubjectFacultyAssignment",
  ATTENDANCE_SESSION: "AttendanceSession",
  ATTENDANCE_RECORD: "AttendanceRecord",
  ASSIGNMENT: "Assignment",
  ASSIGNMENT_SUBMISSION: "AssignmentSubmission",
  RESULT_BATCH: "ResultBatch",
  SEMESTER_RESULT: "SemesterResult",
  SUBJECT_RESULT: "SubjectResult",
  NOTICE: "Notice",
  NOTIFICATION: "Notification",
  NOTIFICATION_RECIPIENT: "NotificationReceipant",
} as const;

export const AUDIT_ENTITY_TYPES = [
  AUDIT_ENTITY_TYPE.USER,
  AUDIT_ENTITY_TYPE.STUDENT,
  AUDIT_ENTITY_TYPE.FACULTY,
  AUDIT_ENTITY_TYPE.CLASS,
  AUDIT_ENTITY_TYPE.CLASS_ENROLLMENT,
  AUDIT_ENTITY_TYPE.SUBJECT,
  AUDIT_ENTITY_TYPE.SUBJECT_FACULTY_ASSIGNMENT,
  AUDIT_ENTITY_TYPE.ATTENDANCE_SESSION,
  AUDIT_ENTITY_TYPE.ATTENDANCE_RECORD,
  AUDIT_ENTITY_TYPE.ASSIGNMENT,
  AUDIT_ENTITY_TYPE.ASSIGNMENT_SUBMISSION,
  AUDIT_ENTITY_TYPE.RESULT_BATCH,
  AUDIT_ENTITY_TYPE.SEMESTER_RESULT,
  AUDIT_ENTITY_TYPE.SUBJECT_RESULT,
  AUDIT_ENTITY_TYPE.NOTICE,
  AUDIT_ENTITY_TYPE.NOTIFICATION,
  AUDIT_ENTITY_TYPE.NOTIFICATION_RECIPIENT,
] as const;

export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[number];

/**
 * Canonical audit verbs. Role lists below say who may perform them.
 * Format: `entity.verb` so logs stay filterable (`student.promote`, `result_batch.publish`).
 */
export const AUDIT_ACTION = {
  AUTH_LOGIN: "auth.login",
  AUTH_LOGOUT: "auth.logout",
  AUTH_SIGNUP: "auth.signup",
  AUTH_GOOGLE_LOGIN: "auth.google_login",
  AUTH_FORGOT_PASSWORD: "auth.forgot_password",
  AUTH_RESET_PASSWORD: "auth.reset_password",

  USER_UPDATE_PROFILE: "user.update_profile",
  USER_UPLOAD_AVATAR: "user.upload_avatar",

  STUDENT_CREATE: "student.create",
  STUDENT_UPDATE: "student.update",
  STUDENT_BULK_UPLOAD: "student.bulk_upload",
  STUDENT_PROMOTE: "student.promote",
  STUDENT_PROMOTE_SEMESTER: "student.promote_semester",
  STUDENT_PASSOUT: "student.passout",
  STUDENT_ACTIVATE_SEMESTER: "student.activate_semester",
  STUDENT_FREEZE_SEMESTER: "student.freeze_semester",
  STUDENT_STATUS_UPDATE: "student.status_update",
  STUDENT_COMPLETE_PROFILE: "student.complete_profile",

  FACULTY_CREATE: "faculty.create",
  FACULTY_UPDATE: "faculty.update",
  FACULTY_BULK_UPLOAD: "faculty.bulk_upload",
  FACULTY_STATUS_UPDATE: "faculty.status_update",
  FACULTY_TRANSFER_DEPARTMENT: "faculty.transfer_department",
  FACULTY_UPDATE_AVAILABILITY: "faculty.update_availability",
  FACULTY_ASSIGN_SUBJECT: "faculty.assign_subject",
  FACULTY_ASSIGN_CLASS: "faculty.assign_class",

  CLASS_CREATE: "class.create",
  CLASS_UPDATE: "class.update",
  CLASS_DELETE: "class.delete",

  ENROLLMENT_CREATE: "enrollment.create",
  ENROLLMENT_WITHDRAW: "enrollment.withdraw",

  SUBJECT_CREATE: "subject.create",
  SUBJECT_UPDATE: "subject.update",
  SUBJECT_ACTIVATE: "subject.activate",
  SUBJECT_DEACTIVATE: "subject.deactivate",
  SUBJECT_ASSIGN_DEPARTMENT: "subject.assign_department",
  SUBJECT_ASSIGN_SEMESTER: "subject.assign_semester",
  SUBJECT_BULK_UPLOAD: "subject.bulk_upload",

  ATTENDANCE_SESSION_START: "attendance_session.start",
  ATTENDANCE_SESSION_CLOSE: "attendance_session.close",
  ATTENDANCE_RECORD_MARK_CODE: "attendance_record.mark_code",
  ATTENDANCE_RECORD_MARK_QR: "attendance_record.mark_qr",
  ATTENDANCE_RECORD_UPDATE: "attendance_record.update",

  ASSIGNMENT_CREATE: "assignment.create",
  ASSIGNMENT_UPDATE: "assignment.update",
  ASSIGNMENT_PUBLISH: "assignment.publish",
  ASSIGNMENT_UNPUBLISH: "assignment.unpublish",
  ASSIGNMENT_DELETE: "assignment.delete",

  ASSIGNMENT_SUBMISSION_CREATE: "assignment_submission.create",
  ASSIGNMENT_SUBMISSION_UPDATE: "assignment_submission.update",
  ASSIGNMENT_SUBMISSION_GRADE: "assignment_submission.grade",

  RESULT_BATCH_CREATE: "result_batch.create",
  RESULT_BATCH_UPDATE: "result_batch.update",
  RESULT_BATCH_PUBLISH: "result_batch.publish",
  RESULT_BATCH_UNPUBLISH: "result_batch.unpublish",
  RESULT_BATCH_UPLOAD_MARKSHEET: "result_batch.upload_marksheet",
  RESULT_BATCH_DOWNLOAD_TEMPLATE: "result_batch.download_template",

  SEMESTER_RESULT_CREATE: "semester_result.create",
  SEMESTER_RESULT_UPDATE: "semester_result.update",
  SUBJECT_RESULT_CREATE: "subject_result.create",
  SUBJECT_RESULT_UPDATE: "subject_result.update",

  NOTICE_CREATE: "notice.create",
  NOTICE_UPDATE: "notice.update",
  NOTICE_DELETE: "notice.delete",

  NOTIFICATION_READ: "notification.read",
  NOTIFICATION_READ_ALL: "notification.read_all",

  CONTACT_SUBMIT: "contact.submit",
  TIMETABLE_DOWNLOAD: "timetable.download",
} as const;

export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];

const SHARED_AUDIT_ACTIONS = [
  AUDIT_ACTION.AUTH_LOGIN,
  AUDIT_ACTION.AUTH_LOGOUT,
  AUDIT_ACTION.AUTH_FORGOT_PASSWORD,
  AUDIT_ACTION.AUTH_RESET_PASSWORD,
  AUDIT_ACTION.USER_UPDATE_PROFILE,
  AUDIT_ACTION.USER_UPLOAD_AVATAR,
  AUDIT_ACTION.NOTIFICATION_READ,
  AUDIT_ACTION.NOTIFICATION_READ_ALL,
] as const;

const ADMIN_ONLY_AUDIT_ACTIONS = [
  AUDIT_ACTION.STUDENT_CREATE,
  AUDIT_ACTION.STUDENT_UPDATE,
  AUDIT_ACTION.STUDENT_BULK_UPLOAD,
  AUDIT_ACTION.STUDENT_PROMOTE,
  AUDIT_ACTION.STUDENT_PROMOTE_SEMESTER,
  AUDIT_ACTION.STUDENT_PASSOUT,
  AUDIT_ACTION.STUDENT_ACTIVATE_SEMESTER,
  AUDIT_ACTION.STUDENT_FREEZE_SEMESTER,
  AUDIT_ACTION.STUDENT_STATUS_UPDATE,

  AUDIT_ACTION.FACULTY_CREATE,
  AUDIT_ACTION.FACULTY_UPDATE,
  AUDIT_ACTION.FACULTY_BULK_UPLOAD,
  AUDIT_ACTION.FACULTY_STATUS_UPDATE,
  AUDIT_ACTION.FACULTY_TRANSFER_DEPARTMENT,
  AUDIT_ACTION.FACULTY_UPDATE_AVAILABILITY,
  AUDIT_ACTION.FACULTY_ASSIGN_SUBJECT,
  AUDIT_ACTION.FACULTY_ASSIGN_CLASS,

  AUDIT_ACTION.CLASS_CREATE,
  AUDIT_ACTION.CLASS_UPDATE,
  AUDIT_ACTION.CLASS_DELETE,

  AUDIT_ACTION.ENROLLMENT_CREATE,
  AUDIT_ACTION.ENROLLMENT_WITHDRAW,

  AUDIT_ACTION.SUBJECT_CREATE,
  AUDIT_ACTION.SUBJECT_UPDATE,
  AUDIT_ACTION.SUBJECT_ACTIVATE,
  AUDIT_ACTION.SUBJECT_DEACTIVATE,
  AUDIT_ACTION.SUBJECT_ASSIGN_DEPARTMENT,
  AUDIT_ACTION.SUBJECT_ASSIGN_SEMESTER,
  AUDIT_ACTION.SUBJECT_BULK_UPLOAD,

  AUDIT_ACTION.ATTENDANCE_RECORD_UPDATE,

  AUDIT_ACTION.RESULT_BATCH_UPDATE,
  AUDIT_ACTION.RESULT_BATCH_UNPUBLISH,
  AUDIT_ACTION.SEMESTER_RESULT_CREATE,
  AUDIT_ACTION.SEMESTER_RESULT_UPDATE,
  AUDIT_ACTION.SUBJECT_RESULT_CREATE,
  AUDIT_ACTION.SUBJECT_RESULT_UPDATE,

  AUDIT_ACTION.NOTICE_CREATE,
  AUDIT_ACTION.NOTICE_UPDATE,
  AUDIT_ACTION.NOTICE_DELETE,
] as const;

const FACULTY_ONLY_AUDIT_ACTIONS = [
  AUDIT_ACTION.ATTENDANCE_SESSION_START,
  AUDIT_ACTION.ATTENDANCE_SESSION_CLOSE,

  AUDIT_ACTION.ASSIGNMENT_CREATE,
  AUDIT_ACTION.ASSIGNMENT_UPDATE,
  AUDIT_ACTION.ASSIGNMENT_PUBLISH,
  AUDIT_ACTION.ASSIGNMENT_UNPUBLISH,
  AUDIT_ACTION.ASSIGNMENT_DELETE,
  AUDIT_ACTION.ASSIGNMENT_SUBMISSION_GRADE,
] as const;

const STUDENT_ONLY_AUDIT_ACTIONS = [
  AUDIT_ACTION.AUTH_SIGNUP,
  AUDIT_ACTION.AUTH_GOOGLE_LOGIN,
  AUDIT_ACTION.STUDENT_COMPLETE_PROFILE,
  AUDIT_ACTION.ATTENDANCE_RECORD_MARK_CODE,
  AUDIT_ACTION.ATTENDANCE_RECORD_MARK_QR,
  AUDIT_ACTION.ASSIGNMENT_SUBMISSION_CREATE,
  AUDIT_ACTION.ASSIGNMENT_SUBMISSION_UPDATE,
  AUDIT_ACTION.CONTACT_SUBMIT,
] as const;

const ADMIN_AND_FACULTY_AUDIT_ACTIONS = [
  AUDIT_ACTION.RESULT_BATCH_CREATE,
  AUDIT_ACTION.RESULT_BATCH_PUBLISH,
  AUDIT_ACTION.RESULT_BATCH_UPLOAD_MARKSHEET,
  AUDIT_ACTION.RESULT_BATCH_DOWNLOAD_TEMPLATE,
] as const;

const FACULTY_AND_STUDENT_AUDIT_ACTIONS = [
  AUDIT_ACTION.TIMETABLE_DOWNLOAD,
] as const;

export const ADMIN_AUDIT_ACTIONS = [
  ...SHARED_AUDIT_ACTIONS,
  ...ADMIN_ONLY_AUDIT_ACTIONS,
  ...ADMIN_AND_FACULTY_AUDIT_ACTIONS,
] as const;

export const FACULTY_AUDIT_ACTIONS = [
  ...SHARED_AUDIT_ACTIONS,
  ...FACULTY_ONLY_AUDIT_ACTIONS,
  ...ADMIN_AND_FACULTY_AUDIT_ACTIONS,
  ...FACULTY_AND_STUDENT_AUDIT_ACTIONS,
] as const;

export const STUDENT_AUDIT_ACTIONS = [
  ...SHARED_AUDIT_ACTIONS,
  ...STUDENT_ONLY_AUDIT_ACTIONS,
  ...FACULTY_AND_STUDENT_AUDIT_ACTIONS,
] as const;

export const AUDIT_ACTIONS_BY_ROLE = {
  admin: ADMIN_AUDIT_ACTIONS,
  faculty: FACULTY_AUDIT_ACTIONS,
  student: STUDENT_AUDIT_ACTIONS,
} as const;

export const ALL_AUDIT_ACTIONS = [
  ...SHARED_AUDIT_ACTIONS,
  ...ADMIN_ONLY_AUDIT_ACTIONS,
  ...FACULTY_ONLY_AUDIT_ACTIONS,
  ...STUDENT_ONLY_AUDIT_ACTIONS,
  ...ADMIN_AND_FACULTY_AUDIT_ACTIONS,
  ...FACULTY_AND_STUDENT_AUDIT_ACTIONS,
] as const;

export type AdminAuditAction = (typeof ADMIN_AUDIT_ACTIONS)[number];
export type FacultyAuditAction = (typeof FACULTY_AUDIT_ACTIONS)[number];
export type StudentAuditAction = (typeof STUDENT_AUDIT_ACTIONS)[number];
