import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
// import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com " />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Bitcount+Grid+Single:wght@100..900&family=Bitcount+Single+Ink:wght@100..900&family=Comfortaa:wght@300..700&family=Delius&family=Funnel+Display:wght@300..800&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Libertinus+Mono&family=Noto+Sans+Devanagari:wght@100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){if(window.__orbitAuthEntryGuard)return;window.__orbitAuthEntryGuard=true;window.addEventListener('pageshow',function(e){if(!e.persisted)return;var p=location.pathname;if(p==='/'||p.indexOf('/landingPage')===0||p.indexOf('/forgotPassword')===0||p.indexOf('/reset-password')===0)location.reload();});})();`,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
        

<Toaster
  position="top-right"
  gutter={10}
  toastOptions={{
    duration: 4000,

    className:
      "min-w-[340px] rounded-xl border border-gray-200 bg-white shadow-xl px-4 py-4 text-sm font-medium flex items-center gap-3",

    success: {
      className:
        "border-l-4 border-l-green-500 bg-white text-gray-800 shadow-md",
      iconTheme: {
        primary: "#22c55e",
        secondary: "#ffffff",
      },
    },

    error: {
      className:
        "border-l-4 border-l-red-500 bg-white text-gray-800 shadow-md",
      iconTheme: {
        primary: "#ef4444",
        secondary: "#ffffff",
      },
    },

    loading: {
      className:
        "border-l-4 border-l-blue-500 bg-white text-gray-800 shadow-md",
    },
  }}
/>
        </body>
    </html>
  );
}

export const metadata: Metadata = {
  metadataBase : new URL("https://vector-phi-rosy.vercel.app/landingPage"),

  title: {
    default: "IIT Dholakhpur | Engineering & Technology, Nuapada",
    template: "%s | IIT Dholakhpur",

    
  },

  description:
    "Our College provides undergraduate and postgraduate programs in engineering, technology and applied sciences.",


    applicationName: "IIT Dholakhpur",

    keywords: [
      "engineering college",
      "BTech",
      "computer science",
      "college",
      "IIT Dholakhpur"
    ],

    authors: [
      {
        name: "IIT Dholakhpur",
      },
    ],

    robots: {
      index: true,
      follow: true,
    },

    openGraph: {
      type: "website",
      locale: "en_IN",
      siteName: "IIT Dholakhpur",
      title: "IIT Dholakhpur | Engineering & Technology, Nuapada",
      description:
        "Discover programs, faculty, admissions, events and academic information.",
      images: [
        {
          url: "/public/campus1.jpg",
          width: 1200,
          height: 630,
          alt: "IIT Dholakhpur",
        },
      ],
    },

    twitter: {
      card: "summary_large_image",
      title: "Your College | Engineering & Technology",
      description:
        "Explore programs, faculty, admissions and academic information.",
      images: ["/images/og-image.jpg"],
    },

    icons: {
      icon: "/favicon.ico",
    },


  }



