import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com " />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Bitcount+Grid+Single:wght@100..900&family=Bitcount+Single+Ink:wght@100..900&family=Comfortaa:wght@300..700&family=Delius&family=Funnel+Display:wght@300..800&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Libertinus+Mono&family=Noto+Sans+Devanagari:wght@100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />


      </head>
      <body className="min-h-full flex flex-col">
        {children}
        

<Toaster
  position="top-right"
  gutter={10}
  toastOptions={{
    duration: 4000,

    className:
      "min-w-[340px] rounded-xl border border-gray-200 bg-white shadow-xl px-4 py-4 text-sm font-medium flex items-center gap-3",

    success: {
      className:
        "border-l-4 border-l-green-500 bg-white text-gray-800 shadow-md",
      iconTheme: {
        primary: "#22c55e",
        secondary: "#ffffff",
      },
    },

    error: {
      className:
        "border-l-4 border-l-red-500 bg-white text-gray-800 shadow-md",
      iconTheme: {
        primary: "#ef4444",
        secondary: "#ffffff",
      },
    },

    loading: {
      className:
        "border-l-4 border-l-blue-500 bg-white text-gray-800 shadow-md",
    },
  }}
/>
        </body>
    </html>
  );
}
