import fs from "fs";
import path from "path";
import { DepartmentType, ExamResultType } from "@/constant/Constant";
import Connect from "@/dbConnect/connect";
import { createRequestLogger } from "@/lib/requestLogger";
import { Student } from "@/models";
import type { IUser } from "@/models/user";
import ExcelJS from "exceljs";

const COLLEGE_NAME = "IIT DHOLAKPUR ENGINEERING COLLEGE";
const LOGO_PATH = path.join(process.cwd(), "public", "iitblogo.png");

type PopulatedStudent = {
  userId: Pick<IUser, "username" | "email"> | null;
  rollNumber?: string;
};

export type TemplateRowData = {
  rollNumber: string;
  name: string;
  email: string;
};

export type TemplateHeaderData = {
  semester: number;
  batch: string;
  department: DepartmentType;
  section?: string;
  subject: string;
  subjectCode: string;
  exam: ExamResultType;
  academicYear?: string;
};

export type TemplatePayload = {
  header: TemplateHeaderData;
  rows: TemplateRowData[];
  count: number;
};

export type TemplateRequestBody = {
  semester: number | string;
  batch: string;
  department: string;
  section?: string;
  subject: string;
  subjectCode: string;
  exam: string;
  academicYear?: string;
};

export async function getTemplateData(
  body: TemplateRequestBody,
): Promise<
  | { success: true; data: TemplatePayload }
  | { success: false; message: string; status: number }
> {
  const logger = createRequestLogger();
  await Connect();

  const {
    semester,
    batch,
    department,
    section,
    subject,
    subjectCode,
    exam,
    academicYear,
  } = body;

  if (!semester || !batch || !department || !subject || !subjectCode || !exam) {
    logger.warn({}, "No data is received");
    return { success: false, message: "Required fields are missing", status: 400 };
  }

  const filter: Record<string, unknown> = {
    semester: Number(semester),
    batch,
    department,
    status: "active",
  };
  if (section) filter.section = section;

  const studentInfo = (await Student.find(filter)
    .populate("userId", "username email")
    .sort({ rollNumber: 1 })
    .lean()) as unknown as PopulatedStudent[];

  if (!studentInfo.length) {
    logger.warn({ filter }, "No student found");
    return {
      success: false,
      message: "No students found for the selected filters",
      status: 404,
    };
  }

  const rows: TemplateRowData[] = studentInfo.map((student) => ({
    rollNumber: student.rollNumber || "—",
    name: student.userId?.username || "—",
    email: student.userId?.email || "—",
  }));

  const header: TemplateHeaderData = {
    semester: Number(semester),
    batch,
    department: department as DepartmentType,
    section,
    subject,
    subjectCode,
    exam: exam as ExamResultType,
    academicYear,
  };

  return {
    success: true,
    data: { header, rows, count: rows.length },
  };
}

function applyPrintFooter(
  worksheet: ExcelJS.Worksheet,
  generatedOn: string,
  generatedBy: string,
) {
  // Excel print footer codes: &L left, &C center, &R right, &P page, &N total pages
  worksheet.headerFooter.oddFooter = [
    `&LGenerated on: ${generatedOn}`,
    `&CGenerated by: ${generatedBy}`,
    `&RPage &P of &N`,
  ].join("");
  worksheet.headerFooter.evenFooter = worksheet.headerFooter.oddFooter;
  worksheet.pageSetup.fitToPage = true;
  worksheet.pageSetup.fitToWidth = 1;
  worksheet.pageSetup.fitToHeight = 0;
  worksheet.pageSetup.orientation = "portrait";
  worksheet.pageSetup.margins = {
    left: 0.5,
    right: 0.5,
    top: 0.6,
    bottom: 0.75,
    header: 0.3,
    footer: 0.4,
  };
}

/** Builds an Excel marks template buffer from prepared student data */
export async function generateMarksTemplateExcel(
  templateData: TemplatePayload,
  options?: { generatedBy?: string },
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = options?.generatedBy || "College Admin";
  workbook.created = new Date();

  const worksheet = workbook.addWorksheet("Marks Entry");
  const generatedOn = new Date().toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  const generatedBy = options?.generatedBy?.trim() || "College Admin";

  // 1) Logo + institution header
  worksheet.mergeCells("B1:F2");
  const heading = worksheet.getCell("B1");
  heading.value = COLLEGE_NAME;
  heading.font = { size: 16, bold: true, color: { argb: "FFFFFFFF" } };
  heading.alignment = { vertical: "middle", horizontal: "center" };
  heading.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "1E3A8A" },
  };
  worksheet.getCell("A1").fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "1E3A8A" },
  };
  worksheet.getCell("A2").fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "1E3A8A" },
  };
  worksheet.getRow(1).height = 36;
  worksheet.getRow(2).height = 36;

  if (fs.existsSync(LOGO_PATH)) {
    const logoId = workbook.addImage({
      buffer: fs.readFileSync(LOGO_PATH) as unknown as ExcelJS.Buffer,
      extension: "png",
    });
    worksheet.addImage(logoId, {
      tl: { col: 0.15, row: 0.15 },
      ext: { width: 58, height: 58 },
      editAs: "oneCell",
    });
  }

  // 2) Header info (exam / class meta)
  const meta: [string, string | number][] = [
    ["Department", templateData.header.department],
    ["Semester", templateData.header.semester],
    ["Batch", templateData.header.batch],
    ["Subject", templateData.header.subject],
    ["Subject Code", templateData.header.subjectCode],
    ["Exam", templateData.header.exam],
  ];
  if (templateData.header.academicYear) {
    meta.push(["Academic Year", templateData.header.academicYear]);
  }

  let rowCursor = 4;
  for (const [label, value] of meta) {
    worksheet.getCell(`A${rowCursor}`).value = label;
    worksheet.getCell(`A${rowCursor}`).font = {
      bold: true,
      color: { argb: "334155" },
    };
    worksheet.getCell(`B${rowCursor}`).value = value;
    rowCursor += 1;
  }

  // 3) Instructions (after header, before student data)
  rowCursor += 1;
  worksheet.mergeCells(`A${rowCursor}:F${rowCursor}`);
  const instructionTitle = worksheet.getCell(`A${rowCursor}`);
  instructionTitle.value = "MARKS ENTRY INSTRUCTIONS";
  instructionTitle.font = { bold: true, size: 11, color: { argb: "1E3A8A" } };
  instructionTitle.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "EEF2FF" },
  };
  rowCursor += 1;

  const instructions = [
    "1. Do not edit Roll Number, Name, or Email.",
    "2. Enter only Obtained Marks.",
    "3. Marks should be between 0 and Maximum Marks (100).",
    "4. Leave Obtained Marks blank if absent.",
    "5. Do not delete or reorder rows.",
  ];

  for (const line of instructions) {
    worksheet.mergeCells(`A${rowCursor}:F${rowCursor}`);
    const cell = worksheet.getCell(`A${rowCursor}`);
    cell.value = line;
    cell.font = { size: 10, color: { argb: "475569" } };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "F8FAFC" },
    };
    rowCursor += 1;
  }

  // 4) Student data table
  rowCursor += 1;
  const tableHeaderRowNumber = rowCursor;
  const headerValues = [
    "Sl No",
    "Roll No",
    "Student Name",
    "Email",
    "Maximum Marks",
    "Obtained Marks",
  ];
  headerValues.forEach((value, index) => {
    const cell = worksheet.getCell(rowCursor, index + 1);
    cell.value = value;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.alignment = { horizontal: "center" };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "4F46E5" },
    };
    cell.border = {
      top: { style: "thin" },
      left: { style: "thin" },
      bottom: { style: "thin" },
      right: { style: "thin" },
    };
  });
  rowCursor += 1;

  templateData.rows.forEach((student, index) => {
    const values = [
      index + 1,
      student.rollNumber,
      student.name,
      student.email,
      100,
      "",
    ];
    values.forEach((value, colIndex) => {
      const cell = worksheet.getCell(rowCursor, colIndex + 1);
      cell.value = value;
      cell.border = {
        top: { style: "thin" },
        left: { style: "thin" },
        bottom: { style: "thin" },
        right: { style: "thin" },
      };
      if (colIndex < 5) {
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: "F8FAFC" },
        };
      }
    });
    rowCursor += 1;
  });

  // 5) Footer at the end of the sheet
  rowCursor += 1;
  worksheet.mergeCells(`A${rowCursor}:F${rowCursor}`);
  const footerTitle = worksheet.getCell(`A${rowCursor}`);
  footerTitle.value = "— End of Marks Template —";
  footerTitle.font = { italic: true, size: 10, color: { argb: "94A3B8" } };
  footerTitle.alignment = { horizontal: "center" };
  rowCursor += 1;

  worksheet.getCell(`A${rowCursor}`).value = "Generated on";
  worksheet.getCell(`A${rowCursor}`).font = {
    bold: true,
    color: { argb: "334155" },
  };
  worksheet.getCell(`B${rowCursor}`).value = generatedOn;
  rowCursor += 1;

  worksheet.getCell(`A${rowCursor}`).value = "Generated by";
  worksheet.getCell(`A${rowCursor}`).font = {
    bold: true,
    color: { argb: "334155" },
  };
  worksheet.getCell(`B${rowCursor}`).value = generatedBy;

  worksheet.columns = [
    { width: 14 },
    { width: 14 },
    { width: 24 },
    { width: 28 },
    { width: 16 },
    { width: 16 },
  ];

  worksheet.views = [{ state: "frozen", ySplit: tableHeaderRowNumber }];
  applyPrintFooter(worksheet, generatedOn, generatedBy);

  const arrayBuffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(arrayBuffer);
}
