import ExcelJS from "exceljs";
import mongoose from "mongoose";
import Connect from "@/dbConnect/connect";
import { ACADEMIC_YEAR, EXAM_RESULT_TYPE } from "@/constant/Constant";
import { Student } from "@/models/student.model";
import { Subject } from "@/models/subject.model";
import { ResultBatch } from "@/models/resultBatch.model";
import { SemesterResult } from "@/models/semesterResult";
import { SubjectResult } from "@/models/subjectResult";

export type MarksheetRowError = {
  row: number;
  errors: string[];
};

export type ParsedMarksheetHeader = {
  department: string;
  semester: number;
  batch: string;
  subject: string;
  subjectCode: string;
  exam: string;
  academicYear: string;
};

export type ParsedMarksheetRow = {
  excelRow: number;
  rollNo: string;
  name: string;
  email: string;
  maximumMarks: number;
  obtainedMarks: number | null; // null = blank / absent
};

function cellText(value: ExcelJS.CellValue): string {
  if (value == null) return "";
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return String(value).trim();
  }
  if (typeof value === "object" && "text" in value && typeof value.text === "string") {
    return value.text.trim();
  }
  if (typeof value === "object" && "result" in value) {
    return String(value.result ?? "").trim();
  }
  return String(value).trim();
}

function gradeFromMarks(obtained: number, maximum: number): string {
  const pct = maximum > 0 ? (obtained / maximum) * 100 : 0;
  if (pct >= 90) return "E";
  if (pct >= 80) return "A+";
  if (pct >= 70) return "A";
  if (pct >= 60) return "B+";
  if (pct >= 50) return "B";
  if (pct >= 40) return "C";
  return "F";
}

function gradePoint(grade: string): number {
  const map: Record<string, number> = {
    E: 10,
    "A+": 9,
    A: 8,
    "B+": 7,
    B: 6,
    C: 5,
    F: 0,
  };
  return map[grade] ?? 0;
}

export async function parseMarksheetBuffer(buffer: Buffer): Promise<{
  header: ParsedMarksheetHeader;
  rows: ParsedMarksheetRow[];
}> {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(buffer as unknown as ExcelJS.Buffer);
  const worksheet = workbook.worksheets[0];
  if (!worksheet) {
    throw new Error("The uploaded file has no worksheet.");
  }

  const meta: Record<string, string> = {};
  let headerRowNumber = -1;

  worksheet.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    const key = cellText(row.getCell(1).value);
    const value = cellText(row.getCell(2).value);
    const keyLower = key.toLowerCase();
    const valueLower = value.toLowerCase();

    if (keyLower === "sl no" && valueLower === "roll no") {
      headerRowNumber = rowNumber;
      return;
    }

    if (headerRowNumber < 0 && key && value) {
      meta[key] = value;
    }
  });

  if (headerRowNumber < 0) {
    throw new Error(
      'Could not find the marks table. Make sure the file has columns "Sl No" and "Roll No". Download a fresh template and try again.',
    );
  }

  const department = meta["Department"] || "";
  const semester = Number(meta["Semester"]);
  const batch = meta["Batch"] || "";
  const subject = meta["Subject"] || "";
  const subjectCode = meta["Subject Code"] || meta["SubjectCode"] || "";
  const exam = meta["Exam"] || "";
  const academicYear = meta["Academic Year"] || meta["AcademicYear"] || "2025-2026";

  const rows: ParsedMarksheetRow[] = [];

  for (let r = headerRowNumber + 1; r <= worksheet.rowCount; r++) {
    const row = worksheet.getRow(r);
    const rollNo = cellText(row.getCell(2).value);
    const firstCol = cellText(row.getCell(1).value);

    // Stop at footer
    if (
      firstCol.toLowerCase().includes("end of marks") ||
      firstCol.toLowerCase() === "generated on" ||
      firstCol.toLowerCase() === "generated by"
    ) {
      break;
    }

    if (!rollNo || rollNo === "—") continue;

    const maxRaw = cellText(row.getCell(5).value);
    const obtainedRaw = cellText(row.getCell(6).value);
    const maximumMarks = maxRaw === "" ? 100 : Number(maxRaw);
    const obtainedMarks =
      obtainedRaw === "" ? null : Number(obtainedRaw);

    rows.push({
      excelRow: r,
      rollNo,
      name: cellText(row.getCell(3).value),
      email: cellText(row.getCell(4).value),
      maximumMarks: Number.isFinite(maximumMarks) ? maximumMarks : 100,
      obtainedMarks:
        obtainedMarks == null || Number.isNaN(obtainedMarks)
          ? obtainedRaw === ""
            ? null
            : NaN
          : obtainedMarks,
    });
  }

  return {
    header: {
      department,
      semester,
      batch,
      subject,
      subjectCode,
      exam,
      academicYear,
    },
    rows,
  };
}

export async function validateMarksheet(buffer: Buffer): Promise<{
  success: boolean;
  message: string;
  invalidRows: MarksheetRowError[];
  studentCount: number;
  header?: ParsedMarksheetHeader;
  preview?: {
    department: string;
    semester: number;
    batch: string;
    subject: string;
    subjectCode: string;
    exam: string;
    validStudents: number;
  };
}> {
  await Connect();

  let parsed: Awaited<ReturnType<typeof parseMarksheetBuffer>>;
  try {
    parsed = await parseMarksheetBuffer(buffer);
  } catch (err) {
    return {
      success: false,
      message: err instanceof Error ? err.message : "Invalid marksheet file",
      invalidRows: [{ row: 0, errors: [err instanceof Error ? err.message : "Invalid file"] }],
      studentCount: 0,
    };
  }

  const { header, rows } = parsed;
  const invalidRows: MarksheetRowError[] = [];

  if (!header.department) {
    invalidRows.push({ row: 0, errors: ["Department is missing in the template header."] });
  }
  if (!header.semester || Number.isNaN(header.semester)) {
    invalidRows.push({ row: 0, errors: ["Semester is missing or invalid in the template header."] });
  }
  if (!header.batch) {
    invalidRows.push({ row: 0, errors: ["Batch is missing in the template header."] });
  }
  if (!header.subjectCode) {
    invalidRows.push({ row: 0, errors: ["Subject Code is missing in the template header."] });
  }
  if (!header.exam || !(EXAM_RESULT_TYPE as readonly string[]).includes(header.exam)) {
    invalidRows.push({
      row: 0,
      errors: [`Exam must be one of: ${EXAM_RESULT_TYPE.join(", ")}. Found "${header.exam || "empty"}".`],
    });
  }
  if (
    header.academicYear &&
    !(ACADEMIC_YEAR as readonly string[]).includes(header.academicYear)
  ) {
    invalidRows.push({
      row: 0,
      errors: [`Academic Year "${header.academicYear}" is not valid.`],
    });
  }

  if (!rows.length) {
    invalidRows.push({
      row: 0,
      errors: ["No student mark rows found. Fill Obtained Marks and keep the student rows from the template."],
    });
  }

  const subject = await Subject.findOne({
    subjectCode: header.subjectCode.trim().toUpperCase(),
  } as Record<string, unknown>).lean()
    || await Subject.findOne({
      subjectCode: header.subjectCode.trim(),
    } as Record<string, unknown>).lean();

  if (!subject && header.subjectCode) {
    invalidRows.push({
      row: 0,
      errors: [`Subject with code "${header.subjectCode}" was not found in the system.`],
    });
  }

  const students = await Student.find({
    department: header.department,
    semester: header.semester,
    batch: header.batch,
    status: "active",
  } as Record<string, unknown>)
    .select("rollNumber")
    .lean();

  const studentByRoll = new Map(
    students
      .filter((s) => s.rollNumber)
      .map((s) => [String(s.rollNumber).trim().toUpperCase(), s]),
  );

  const seen = new Map<string, number>();

  for (const row of rows) {
    const errors: string[] = [];
    const rollKey = row.rollNo.trim().toUpperCase();

    if (seen.has(rollKey)) {
      errors.push(
        `Duplicate roll number "${row.rollNo}" (also on row ${seen.get(rollKey)}).`,
      );
    } else {
      seen.set(rollKey, row.excelRow);
    }

    if (!studentByRoll.has(rollKey)) {
      errors.push(
        `Roll number "${row.rollNo}" is not an active student in ${header.department} · Sem ${header.semester} · Batch ${header.batch}.`,
      );
    }

    if (row.maximumMarks <= 0 || row.maximumMarks > 100) {
      errors.push("Maximum marks must be between 1 and 100.");
    }

    if (row.obtainedMarks === null) {
      // blank allowed → not_attended
    } else if (Number.isNaN(row.obtainedMarks)) {
      errors.push("Obtained marks must be a number.");
    } else if (row.obtainedMarks < 0) {
      errors.push("Obtained marks cannot be negative.");
    } else if (row.obtainedMarks > 100) {
      errors.push(`Obtained marks (${row.obtainedMarks}) cannot exceed 100.`);
    } else if (row.obtainedMarks > row.maximumMarks) {
      errors.push(
        `Obtained marks (${row.obtainedMarks}) cannot exceed maximum marks (${row.maximumMarks}).`,
      );
    }

    if (errors.length) {
      invalidRows.push({ row: row.excelRow, errors });
    }
  }

  // Missing expected students who have no row at all — warn as soft? User said validate entered data.
  // Require all students from cohort to be present in file:
  for (const [rollKey, student] of studentByRoll) {
    if (!seen.has(rollKey)) {
      invalidRows.push({
        row: 0,
        errors: [
          `Missing marks row for roll number "${student.rollNumber}". Keep all students from the downloaded template.`,
        ],
      });
    }
  }

  invalidRows.sort((a, b) => a.row - b.row);

  if (invalidRows.length) {
    return {
      success: false,
      message: `Found ${invalidRows.length} issue(s). Fix the file and re-upload.`,
      invalidRows,
      studentCount: rows.length,
      header,
    };
  }

  return {
    success: true,
    message: "Validation passed. Ready to publish.",
    invalidRows: [],
    studentCount: rows.length,
    header,
    preview: {
      department: header.department,
      semester: header.semester,
      batch: header.batch,
      subject: header.subject || subject?.subjectName || header.subjectCode,
      subjectCode: header.subjectCode,
      exam: header.exam,
      validStudents: rows.length,
    },
  };
}

export async function publishMarksheet(buffer: Buffer): Promise<{
  success: boolean;
  message: string;
  invalidRows?: MarksheetRowError[];
  studentCount?: number;
  batchId?: string;
}> {
  const validation = await validateMarksheet(buffer);
  if (!validation.success || !validation.header) {
    return {
      success: false,
      message: validation.message,
      invalidRows: validation.invalidRows,
      studentCount: validation.studentCount,
    };
  }

  const { header } = validation;
  const parsed = await parseMarksheetBuffer(buffer);

  const subject = await Subject.findOne({
    subjectCode: header.subjectCode.trim().toUpperCase(),
  } as Record<string, unknown>).lean()
    || await Subject.findOne({
      subjectCode: header.subjectCode.trim(),
    } as Record<string, unknown>).lean();

  if (!subject) {
    return {
      success: false,
      message: `Subject "${header.subjectCode}" not found.`,
      invalidRows: [{ row: 0, errors: [`Subject "${header.subjectCode}" not found.`] }],
    };
  }

  const title = `${header.department} Sem ${header.semester} ${header.subjectCode} ${header.exam} (${header.batch})`;

  let batch = await ResultBatch.findOne({
    department: header.department,
    semester: header.semester,
    batch: header.batch,
    ExamType: header.exam,
    subjectId: subject._id,
    academicYear: header.academicYear,
  } as Record<string, unknown>);

  if (batch && batch.status === "published") {
    return {
      success: false,
      message:
        "Results for this subject/exam are already published and locked. Contact admin to revise.",
      invalidRows: [
        {
          row: 0,
          errors: ["This result batch is already published and cannot be overwritten."],
        },
      ],
    };
  }

  if (!batch) {
    batch = await ResultBatch.create({
      title,
      department: header.department,
      semester: header.semester,
      academicYear: header.academicYear,
      ExamType: header.exam,
      batch: header.batch,
      subjectId: subject._id,
      status: "draft",
    } as Record<string, unknown>);
  }

  if (!batch) {
    return { success: false, message: "Failed to create result batch." };
  }

  // Clear previous draft entries for this batch
  const existingSemester = await SemesterResult.find({
    resultBatch: batch._id,
  } as Record<string, unknown>).select("_id");
  const existingIds = existingSemester.map((r) => r._id);
  if (existingIds.length) {
    await SubjectResult.deleteMany({
      semesterResultId: { $in: existingIds },
    } as Record<string, unknown>);
    await SemesterResult.deleteMany({
      _id: { $in: existingIds },
    } as Record<string, unknown>);
  }

  const students = await Student.find({
    department: header.department,
    semester: header.semester,
    batch: header.batch,
    status: "active",
  } as Record<string, unknown>).lean();

  const studentByRoll = new Map(
    students
      .filter((s) => s.rollNumber)
      .map((s) => [String(s.rollNumber).trim().toUpperCase(), s]),
  );

  const credits = Number(subject.credits) || 0;

  const ranked = [...parsed.rows]
    .map((r) => ({
      ...r,
      sortMarks: r.obtainedMarks == null ? -1 : r.obtainedMarks,
    }))
    .sort((a, b) => b.sortMarks - a.sortMarks);

  for (let i = 0; i < ranked.length; i++) {
    const entry = ranked[i];
    const student = studentByRoll.get(entry.rollNo.trim().toUpperCase());
    if (!student) continue;

    const isAbsent = entry.obtainedMarks == null;
    const obtained = isAbsent ? 0 : Number(entry.obtainedMarks);
    const maximum = entry.maximumMarks || 100;
    const grade = isAbsent ? "F" : gradeFromMarks(obtained, maximum);
    const pct = maximum > 0 ? (obtained / maximum) * 100 : 0;
    const resultStatus = isAbsent
      ? "not_attended"
      : pct >= 40
        ? "passed"
        : "failed";
    const gp = isAbsent ? 0 : gradePoint(grade);
    const sgpa = credits > 0 ? Math.round(((gp * credits) / credits) * 10) / 10 : gp;

    const semesterResult = await SemesterResult.create({
      studentId: student._id,
      semester: header.semester,
      resultBatch: batch._id,
      CGPA: sgpa,
      SGPA: sgpa,
      rank: i + 1,
      passStatus: resultStatus === "passed" ? "Pass" : "Fail",
      passStatusDate: new Date(),
      hadBack: resultStatus !== "passed",
    } as Record<string, unknown>);

    if (!semesterResult) continue;

    await SubjectResult.create({
      semesterResultId: semesterResult._id,
      subjectId: subject._id as mongoose.Types.ObjectId,
      grade,
      maximumMarks: maximum,
      obtainedMarks: obtained,
      creditsEarned: resultStatus === "passed" ? credits : 0,
      resultStatus,
    } as Record<string, unknown>);
  }

  batch.status = "published";
  batch.title = title;
  await batch.save();

  return {
    success: true,
    message: `Results published for ${ranked.length} student(s). Subject results are saved and editing is locked.`,
    studentCount: ranked.length,
    batchId: String(batch._id),
  };
}
